language: scala

scala:
  - 2.11.11
  - 2.12.4

jdk:
  - oraclejdk8

script:
  - sbt ++$TRAVIS_SCALA_VERSION clean compile package

after_success:
- ! '[[ $TRAVIS_BRANCH == "master" ]] && { sbt +publish; };'